version: '2'

services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "9998:80"
    links:
      - api:api
  api:
    build: .
    expose:
      - "3000"
    volumes:
      - ./dist:/src/dist
      - ./src/environments:/src/dist/environments
      - ./public:/src/public
    user: node
    command: npm run start:prod --prod
    links:
        - db
        - mail
    depends_on:
        - db
        - mail
  db:
    image: mongo:latest
    environment:
      - MONGO_LOG_DIR=/dev/null
    expose:
        - "27017"
    command: mongod --smallfiles
  mail:
    extends:
      file: mail/docker-compose.yml
      service: mail
    restart: always

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local