version: '2'
services:
  api:
    image: node
    hostname: api
    depends_on:
      - db
    links:
      - "db"
    environment:
      - CORS_ORIGIN=http://localhost:3001,http://localhost:3000
    ports:
      - "127.0.0.1:9999:3000"
#      - "127.0.0.1:9229:9229" # V8 inspector (when NODE_DEBUG=true)
    volumes:
      - ./:/usr/src/app
    user: node
    working_dir: /usr/src/app
    command: bash -c "./config/start_node.sh"
  # SQL and document data store
  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=game
      - POSTGRES_PASSWORD=7uRCSMeGpP
    ports:
      - "5432"
    volumes:
      - ./config:/usr/app/config
