version: '3'

services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8888:80"
    links:
      - api:api
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/src/dist
    user: node
    command: npm run start:prod
