version: '2'
services:
#  nginx:
#    image: nginx
##    read_only: true
#    depends_on:
#      - api
#    ports:
#      - "8080:80"
##      - "8443:443"
#    volumes:
##      - ./config/nginx-snippets:/etc/nginx/snippets:ro
#      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    image: node
    hostname: api
    depends_on:
      - db
    links:
      - "db"
    environment:
      - CORS_ORIGIN=http://localhost:3001,http://localhost:3000
      - DATABASE_URL=postgres://game:7uRCSMeGpP@db:5432/game
    ports:
      - "3000:3000"
      - "127.0.0.1:9229:9229" # V8 inspector (when NODE_DEBUG=true)
    volumes:
      - ./:/usr/src/app
    user: node
    working_dir: /usr/src/app
    command: bash -c "./config/start_node.sh"
  # SQL and document data store
  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=game
      - POSTGRES_PASSWORD=7uRCSMeGpP
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./config:/usr/app/config