version: '3'
services:
  nginx:
    image: nginx
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/log/nginx
      - /var/run
    depends_on:
      - api
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config/nginx-snippets:/etc/nginx/snippets:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    image: node
    hostname: api
    depends_on:
      - db
    environment:
      - CORS_ORIGIN=http://localhost:3001,http://localhost:3000
    expose:
      - "8080"
    ports:
      - "127.0.0.1:9229:9229" # V8 inspector (when NODE_DEBUG=true)
    volumes:
      - yarn:/root/.cache/yarn
      - ./:/usr/src/app
    user: node
    working_dir: /usr/src/app
#    command: node tools/run.js
  # SQL and document data store
  db:
    image: mdillon/postgis
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data