version: '3'

services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8888:80"
    links:
      - api:api
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/src/dist
      - ./src/environments:/src/dist/environments
      - ./logs:/src/logs
    environment:
      - NODE_ENV=production
    user: node
    command: npm run start:prod
    links:
        - db
    depends_on:
        - db
  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles